Style/TrivialAccessors:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Lint/HandleExceptions:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
